preload = ~/.config/hypr/wallpaper.png
preload = ~/.config/hypr/wallpaper-2.png
preload = ~/.config/hypr/wallpaper-3.jpg

# Set initial defaults so it doesn't start empty
wallpaper = eDP-1, ~/.config/hypr/wallpaper.png
wallpaper = DP-2, ~/.config/hypr/wallpaper.png

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper-2.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wallpaper-2.png
    fit_mode = cover
}

exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/random-wallpaper.sh
