general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.2
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(1e1e2e)
    inner_color = rgb(313244)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 15
    check_color = rgb(a6e3a1)
    fail_color = rgb(f38ba8)
    fail_text = <i>$FAIL</i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(cdd6f4)
    font_size = 90
    font_family = Maple Mono NF
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgb(a6adc8)
    font_size = 20
    font_family = Maple Mono NF
    position = 0, 75
    halign = center
    valign = center
}
